# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_App_development
  pool: 5
  username: postgres
  password: Al!jan1990
  host: localhost

test:
  <<: *default
  database: Blog_App_test
  pool: 5
  username: postgres
  password: Al!jan1990
  host: localhost

production:
  <<: *default
  database: Blog_App_production
  pool: 5
  username: postgres
  password: Al!jan1990
  host: localhost
